// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB679syqVtZXA4lf3amFciH4LUs9637W18',
    appId: '1:46168034890:web:bd04bc6e65027a5831e0b3',
    messagingSenderId: '46168034890',
    projectId: 'codebloom-app',
    authDomain: 'codebloom-app.firebaseapp.com',
    storageBucket: 'codebloom-app.firebasestorage.app',
    measurementId: 'G-BW66Z0M050',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPTnD_ZK4rMHqXomMn8BcARM08O6vKCbM',
    appId: '1:46168034890:android:27b8d73183a8834a31e0b3',
    messagingSenderId: '46168034890',
    projectId: 'codebloom-app',
    storageBucket: 'codebloom-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpGmpGOy5OT0cZHjQW1Yl_w_cYL5f9vUA',
    appId: '1:46168034890:ios:4023a6a4468687ed31e0b3',
    messagingSenderId: '46168034890',
    projectId: 'codebloom-app',
    storageBucket: 'codebloom-app.firebasestorage.app',
    iosBundleId: 'com.codebloom.app.codebloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpGmpGOy5OT0cZHjQW1Yl_w_cYL5f9vUA',
    appId: '1:46168034890:ios:4023a6a4468687ed31e0b3',
    messagingSenderId: '46168034890',
    projectId: 'codebloom-app',
    storageBucket: 'codebloom-app.firebasestorage.app',
    iosBundleId: 'com.codebloom.app.codebloom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB679syqVtZXA4lf3amFciH4LUs9637W18',
    appId: '1:46168034890:web:ef1dbe9607a1100b31e0b3',
    messagingSenderId: '46168034890',
    projectId: 'codebloom-app',
    authDomain: 'codebloom-app.firebaseapp.com',
    storageBucket: 'codebloom-app.firebasestorage.app',
    measurementId: 'G-FSP43JQCZR',
  );

}